print("Hello World")
print("Khadija")
print("First name: Khadija , Last name: Muzammil")
print("1,2,3")
print("Hello \n World")
print("Hello \t World")
print("apple, banana, cherry",sep='')
print('1','2','3',sep='')
print("Hello", end='')
print("World")
print("1",end='')
print("2")
print('\"Hello!"')
print("This is backslash\\")
print("I am 18 years old")
print("5\'")
for x in range(1,6):
    print(x)